repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9  # check latest tag on GitHub
    hooks:
      # Formats code — runs on commit
      - id: ruff-format
        stages: [pre-commit]

      # Lints/checks code — runs on push
      - id: ruff
        args: [--fix]
        stages: [pre-push]